language: cpp
compiler:
  - gcc
  - clang
env:
  - CFLAGS=--coverage CXXFLAGS=--coverage
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-dev
  - sudo pip install cpp-coveralls --use-mirrors
script:
  - cmake .
  - make -j4
after_success:
  - coveralls --exclude CMakeFiles --exclude-pattern 'CMake[^\.]*\.c(?:pp)?' --exclude-pattern '[^\.]*\.h' > /dev/null
