language: cpp
compiler:
  - gcc
  - clang
env:
  - BT=SHARED
  - BT=STATIC
matrix:
  include:
    - compiler: gcc
      env: BT=SHARED CFLAGS=--coverage CXXFLAGS=--coverage COVERAGE=1
      fast_finish: true
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install libboost1.48-dev libboost-signals1.48-dev libboost-system1.48-dev libboost-test1.48-dev
  - if [ -n "$COVERAGE" ]; then sudo pip install cpp-coveralls --use-mirrors; fi
script:
  - cmake . -DHYPODERMIC_BUILD_TYPE=$BT
  - make -j4
after_success:
  - if [ -n "$COVERAGE" ]; then coveralls --exclude CMakeFiles --exclude-pattern 'CMake[^\.]*\.c(?:pp)?' --exclude-pattern '[^\.]*\.h' > /dev/null; fi
