language: cpp
compiler:
  - gcc
  - clang
env:
  - BT=SHARED
  - BT=STATIC
matrix:
  include:
    - compiler: gcc
      env: BT=SHARED CFLAGS=--coverage CXXFLAGS=--coverage COVERAGE=1
      fast_finish: true
before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
install:
  - sudo apt-get install libboost1.54-dev libboost-signals1.54-dev libboost-system1.54-dev libboost-test1.54-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ -n "$COVERAGE" ]; then sudo pip install cpp-coveralls --use-mirrors; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - cmake . -DHYPODERMIC_BUILD_TYPE=$BT
  - make -j4
after_success:
  - if [ -n "$COVERAGE" ]; then coveralls --gcov gcov-4.8 --exclude CMakeFiles --exclude-pattern 'CMake[^\.]*\.c(?:pp)?' --exclude-pattern '[^\.]*\.h' > /dev/null; fi
