language: cpp
compiler:
  - gcc
  - clang
env:
  - BT=SHARED
  - BT=STATIC
matrix:
  include:
    - compiler: gcc
      env: BT=SHARED CFLAGS=--coverage CXXFLAGS=--coverage
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-dev libboost-signals-dev libboost-system-dev libboost-test-dev
  - sudo pip install cpp-coveralls --use-mirrors
script:
  - cmake . -DHYPODERMIC_BUILD_TYPE=$BT
  - make -j4
after_success:
  - coveralls --exclude CMakeFiles --exclude-pattern 'CMake[^\.]*\.c(?:pp)?' --exclude-pattern '[^\.]*\.h' > /dev/null
